export type SiteConfig = typeof siteConfig;

export const siteConfig = {
	name: "Info Valorant",
	description: "Visualización de datos del videojuego VALORANT utilizando Valorant-API (https://dash.valorant-api.com/).",
	homedisplay: {
		first: {
			enUS: "Website where you can find Valorant-related information.",
			esES: "Sitio web donde puedes ver información de Valorant.",
			arAE: "الموقع الإلكتروني حيث يمكنك العثور على معلومات متعلقة بلعبة Valorant.",
			deDE: "Website, auf der Sie Valorant-bezogene Informationen finden können.",
			esMX: "Sitio web donde puedes encontrar información relacionada con Valorant.",
			frFR: "Site Web où vous pouvez trouver des informations liées à Valorant.",
			idID: "Situs web di mana Anda dapat menemukan informasi terkait Valorant.",
			itIT: "Sito web dove puoi trovare informazioni relative a Valorant.",
			jaJP: "Valorantに関連する情報を見つけることができるウェブサイト。",
			koKR: "Valorant 관련 정보를 찾을 수 있는 웹사이트입니다.",
			plPL: "Strona internetowa, na której znajdziesz informacje związane z Valorant.",
			ptBR: "Site onde você pode encontrar informações relacionadas ao Valorant.",
			ruRU: "Веб-сайт, где вы можете найти информацию, связанную с Valorant.",
			thTH: "เว็บไซต์ที่คุณสามารถหาข้อมูลเกี่ยวกับ Valorant ได้",
			trTR: "Valorant ile ilgili bilgilere ulaşabileceğiniz bir web sitesi.",
			viVN: "Trang web nơi bạn có thể tìm thông tin liên quan đến Valorant.",
			zhCN: "您可以在此网站上找到与Valorant相关的信息。",
			zhTW: "您可以在此網站上找到與Valorant相關的信息。",
		},
		second: {
			enUS: "The information was obtained from",
			esES: "La información fue obtenida de",
			arAE: "تم الحصول على المعلومات من",
			deDE: "Die Informationen stammen von",
			esMX: "La información fue obtenida de",
			frFR: "Les informations ont été obtenues auprès de",
			idID: "Informasi ini diperoleh dari",
			itIT: "Le informazioni sono state ottenute da",
			jaJP: "情報は次から取得されました",
			koKR: "정보는 다음에서 얻었습니다",
			plPL: "Informacje zostały uzyskane od",
			ptBR: "As informações foram obtidas de",
			ruRU: "Информация была получена из",
			thTH: "ข้อมูลได้รับจาก",
			trTR: "Bilgiler şuradan alındı",
			viVN: "Thông tin được lấy từ",
			zhCN: "信息来自",
			zhTW: "信息來自",
		},
		third: {
			enUS: "thus, we maintain their policies, which you can view in the",
			esES: "por ello mantenemos sus políticas que puede ver en la sección",
			arAE: "لذا نحن نحتفظ بسياساتهم، التي يمكنك مشاهدتها في القسم",
			deDE: "daher halten wir ihre Richtlinien aufrecht, die Sie im",
			esMX: "por ello mantenemos sus políticas que puede ver en la sección",
			frFR: "c'est pourquoi nous maintenons leurs politiques, que vous pouvez consulter dans la",
			idID: "karenanya kami mempertahankan kebijakan mereka, yang dapat Anda lihat di",
			itIT: "quindi manteniamo le loro politiche, che puoi vedere nella sezione",
			jaJP: "したがって、私たちは彼らのポリシーを維持し、それを表示できます",
			koKR: "따라서 우리는 그들의 정책을 유지하며 해당 섹션에서 볼 수 있습니다",
			plPL: "dlatego utrzymujemy ich politykę, którą możesz zobaczyć w sekcji",
			ptBR: "portanto, mantemos suas políticas, que você pode ver na seção",
			ruRU: "поэтому мы поддерживаем их политику, которую вы можете увидеть в разделе",
			thTH: "ดังนั้นเรารักษานโยบายของพวกเขาซึ่งคุณสามารถดูได้ในส่วน",
			trTR: "bu nedenle politikalarını sürdürüyoruz, bunları görebilirsiniz",
			viVN: "do đó, chúng tôi duy trì chính sách của họ, mà bạn có thể xem trong phần",
			zhCN: "因此，我们维护他们的政策，您可以在",
			zhTW: "因此，我們維護他們的政策，您可以在",
		},
		fourth: {
			enUS: "About Us",
			esES: "Acerca de nosotros",
			arAE: "عنا",
			deDE: "Über uns",
			esMX: "Acerca de nosotros",
			frFR: "À propos de nous",
			idID: "Tentang Kami",
			itIT: "Chi siamo",
			jaJP: "私たちについて",
			koKR: "회사 소개",
			plPL: "O nas",
			ptBR: "Sobre nós",
			ruRU: "О нас",
			thTH: "เกี่ยวกับเรา",
			trTR: "Hakkımızda",
			viVN: "Về chúng tôi",
			zhCN: "关于我们",
			zhTW: "關於我們",
		},
		fifth: {
			enUS: "It's important to mention that the website is for academic purposes to showcase programming knowledge, not for profit or to harm Riot Games in any way.",
			esES: "Importante mencionar que el sitio es con fines académicos para demostrar conocimientos como programador, no para lucrar ni perjudicar de ninguna manera a Riot Games.",
			arAE: "من المهم أن نذكر أن الموقع مخصص للأغراض الأكاديمية لعرض المعرفة في مجال البرمجة، وليس للربح أو لإلحاق الضرر بـ Riot Games بأي شكل من الأشكال.",
			deDE: "Es ist wichtig zu erwähnen, dass die Website zu akademischen Zwecken dient, um Programmierkenntnisse zu präsentieren, und nicht für Gewinn oder zur Schädigung von Riot Games in irgendeiner Weise.",
			esMX: "Importante mencionar que el sitio es con fines académicos para demostrar conocimientos como programador, no para lucrar ni perjudicar de ninguna manera a Riot Games.",
			frFR: "Il est important de mentionner que le site est à des fins académiques pour présenter des connaissances en programmation, et non à des fins lucratives ou pour nuire à Riot Games de quelque manière que ce soit.",
			idID: "Penting untuk mencatat bahwa situs web ini untuk tujuan akademis untuk memamerkan pengetahuan pemrograman, bukan untuk keuntungan atau merugikan Riot Games dengan cara apa pun.",
			itIT: "È importante menzionare che il sito web è a scopo accademico per mostrare conoscenze di programmazione, non per scopi di lucro o per danneggiare Riot Games in alcun modo.",
			jaJP: "このウェブサイトはプログラムの知識を展示するための学術的な目的であり、利益を追求したり、Riot Games に対して何らかの方法で害を与えたりするものではありません。",
			koKR: "이 웹 사이트는 프로그래밍 지식을 전시하기 위한 학술적 목적으로 제공되며, 이익을 얻거나 Riot Games를 어떤 방식으로든 손상시키기 위한 것이 아닙니다.",
			plPL: "Warto wspomnieć, że strona internetowa ma na celu prezentację wiedzy programistycznej w celach akademickich, a nie w celach zarobkowych ani w celu szkodzenia Riot Games w jakikolwiek sposób.",
			ptBR: "É importante mencionar que o site é para fins acadêmicos, com o objetivo de mostrar conhecimentos em programação, e não para fins lucrativos ou para prejudicar a Riot Games de qualquer forma.",
			ruRU: "Важно отметить, что этот сайт предназначен для академических целей, чтобы продемонстрировать знания в программировании, а не для извлечения прибыли или навредить Riot Games каким-либо образом.",
			thTH: "สำคัญที่จะกล่าวถึงว่าเว็บไซต์นี้มีวัตถุประสงค์เพื่อการศึกษาเพื่อแสดงความรู้ในการเขียนโปรแกรม ไม่ใช่เพื่อหวังผลกำไรหรือใช้เพื่อทำความเสียหายให้กับ Riot Games ในทางใดก็ตาม.",
			trTR: "Sitenin akademik amaçlarla programlama bilgisini sergilemek amacıyla olduğunu, kar amacı güdülmediğini veya Riot Games'e herhangi bir şekilde zarar vermek amacı taşımadığını belirtmek önemlidir.",
			viVN: "Quan trọng phải đề cập rằng trang web này dành cho mục đích học thuật để trình bày kiến thức về lập trình, không vì lợi nhuận hoặc gây hại cho Riot Games bằng bất kỳ cách nào.",
			zhCN: "重要的是要提到，该网站用于学术目的，以展示编程知识，而不是出于盈利或以任何方式损害Riot Games。",
			zhTW: "重要的是要提到，該網站用於學術目的，以展示編程知識，而不是出於盈利或以任何方式損害Riot Games。",
		},
	},
	createdBy: {
		enUS: "Created by",
		esES: "Creado por",
		arAE: "تم إنشاؤه بواسطة",
		deDE: "Erstellt von",
		esMX: "Creado por",
		frFR: "Créé par",
		idID: "Dibuat oleh",
		itIT: "Creato da",
		jaJP: "作成者",
		koKR: "만든 사람",
		plPL: "Stworzone przez",
		ptBR: "Criado por",
		ruRU: "Создано",
		thTH: "สร้างโดย",
		trTR: "Oluşturan",
		viVN: "Tạo bởi",
		zhCN: "创建者",
		zhTW: "創建者",
	},
	languaje: {
		spanish: {
			enUS: "Spanish",
			esES: "Español"
		},
		english: {
			enUS: "English",
			esES: "Inglés"
		}
	},
	navItems: {
		home: {
			enUS: "HOME",
			esES: "INICIO",
			arAE: "الصفحة الرئيسية",
			deDE: "STARTSEITE",
			esMX: "INICIO",
			frFR: "ACCUEIL",
			idID: "BERANDA",
			itIT: "HOME",
			jaJP: "ホーム",
			koKR: "홈",
			plPL: "STRONA GŁÓWNA",
			ptBR: "INÍCIO",
			ruRU: "ГЛАВНАЯ",
			thTH: "หน้าหลัก",
			trTR: "ANA SAYFA",
			viVN: "TRANG CHỦ",
			zhCN: "主页",
			zhTW: "首頁",
		},
		agents: {
			enUS: "AGENTS",
			esES: "AGENTES",
			arAE: "وكلاء",
			deDE: "AGENTEN",
			esMX: "AGENTES",
			frFR: "AGENTS",
			idID: "AGEN",
			itIT: "AGENTI",
			jaJP: "エージェント",
			koKR: "요원",
			plPL: "AGENCI",
			ptBR: "AGENTES",
			ruRU: "АГЕНТЫ",
			thTH: "สถาบัน",
			trTR: "AJANSLAR",
			viVN: "ĐẠI LÝ",
			zhCN: "特工",
			zhTW: "特工",
		},
		weapons: {
			enUS: "WEAPONS",
			esES: "ARMAS",
			arAE: "أسلحة",
			deDE: "WAFFEN",
			esMX: "ARMAS",
			frFR: "ARMES",
			idID: "SENJATA",
			itIT: "ARMI",
			jaJP: "武器",
			koKR: "무기",
			plPL: "BROŃ",
			ptBR: "ARMAS",
			ruRU: "ОРУЖИЕ",
			thTH: "อาวุธ",
			trTR: "SİLAHLAR",
			viVN: "VŨ KHÍ",
			zhCN: "武器",
			zhTW: "武器",
		},
		maps: {
			enUS: "MAPS",
			esES: "MAPAS",
			arAE: "خرائط",
			deDE: "KARTEN",
			esMX: "MAPAS",
			frFR: "CARTES",
			idID: "PETA",
			itIT: "MAPPE",
			jaJP: "マップ",
			koKR: "지도",
			plPL: "MAPY",
			ptBR: "MAPAS",
			ruRU: "КАРТЫ",
			thTH: "แผนที่",
			trTR: "HARİTALAR",
			viVN: "BẢN ĐỒ",
			zhCN: "地图",
			zhTW: "地圖",
		},
		cards: {
			enUS: "CARD",
			esES: "CARTAS",
			arAE: "بطاقات",
			deDE: "KARTEN",
			esMX: "CARTAS",
			frFR: "CARTES",
			idID: "KARTU",
			itIT: "CARTE",
			jaJP: "カード",
			koKR: "카드",
			plPL: "KARTY",
			ptBR: "CARTAS",
			ruRU: "КАРТЫ",
			thTH: "การ์ด",
			trTR: "KARTLAR",
			viVN: "THẺ",
			zhCN: "卡片",
			zhTW: "卡片",
		},
		tiers: {
			enUS: "TIERS",
			esES: "RANGOS",
			arAE: "رتب",
			deDE: "STUFEN",
			esMX: "RANGOS",
			frFR: "TIERS",
			idID: "TIER",
			itIT: "LIVELLI",
			jaJP: "ティア",
			koKR: "티어",
			plPL: "RANGI",
			ptBR: "RANKS",
			ruRU: "ТИРЫ",
			thTH: "ระดับ",
			trTR: "SEVİYELER",
			viVN: "HẠNG",
			zhCN: "层级",
			zhTW: "層級",
		},
		about: {
			enUS: "ABOUT",
			esES: "ACERCA DE",
			arAE: "حول",
			deDE: "ÜBER UNS",
			esMX: "ACERCA DE",
			frFR: "À PROPOS DE",
			idID: "TENTANG",
			itIT: "CHI SIAMO",
			jaJP: "について",
			koKR: "정보",
			plPL: "O NAS",
			ptBR: "SOBRE NÓS",
			ruRU: "О НАС",
			thTH: "เกี่ยวกับ",
			trTR: "HAKKIMIZDA",
			viVN: "VỀ CHÚNG TÔI",
			zhCN: "关于",
			zhTW: "關於",
		},
	},
	navSelectedLanguage: [
		{
			language: "es-ES",
			languageFormated: "esES",
			url: "https://flagcdn.com/es.svg"
		},
		{
			language: "ar-AE",
			languageFormated: "arAE",
			url: "https://flagcdn.com/ae.svg"
		},
		{
			language: "de-DE",
			languageFormated: "deDE",
			url: "https://flagcdn.com/de.svg"
		},
		{
			language: "en-US",
			languageFormated: "enUS",
			url: "https://flagcdn.com/us.svg"
		},
		{
			language: "es-MX",
			languageFormated: "esMX",
			url: "https://flagcdn.com/mx.svg"
		},
		{
			language: "fr-FR",
			languageFormated: "frFR",
			url: "https://flagcdn.com/fr.svg"
		},
		{
			language: "id-ID",
			languageFormated: "idID",
			url: "https://flagcdn.com/id.svg"
		},
		{
			language: "it-IT",
			languageFormated: "itIT",
			url: "https://flagcdn.com/it.svg"
		},
		{
			language: "ja-JP",
			languageFormated: "jaJP",
			url: "https://flagcdn.com/jp.svg"
		},
		{
			language: "ko-KR",
			languageFormated: "koKR",
			url: "https://flagcdn.com/kr.svg"
		},
		{
			language: "pl-PL",
			languageFormated: "plPL",
			url: "https://flagcdn.com/pl.svg"
		},
		{
			language: "pt-BR",
			languageFormated: "ptBR",
			url: "https://flagcdn.com/br.svg"
		},
		{
			language: "ru-RU",
			languageFormated: "ruRU",
			url: "https://flagcdn.com/ru.svg"
		},
		{
			language: "th-TH",
			languageFormated: "thTH",
			url: "https://flagcdn.com/th.svg"
		},
		{
			language: "tr-TR",
			languageFormated: "trTR",
			url: "https://flagcdn.com/tr.svg"
		},
		{
			language: "vi-VN",
			languageFormated: "viVN",
			url: "https://flagcdn.com/vn.svg"
		},
		{
			language: "zh-CN",
			languageFormated: "zhCN",
			url: "https://flagcdn.com/cn.svg"
		},
		{
			language: "zh-TW",
			languageFormated: "zhTW",
			url: "https://flagcdn.com/tw.svg"
		}
	],
	navMenuItems: [
		{
			label: "Profile",
			href: "/profile",
		},
		{
			label: "Dashboard",
			href: "/dashboard",
		},
		{
			label: "Projects",
			href: "/projects",
		},
		{
			label: "Team",
			href: "/team",
		},
		{
			label: "Calendar",
			href: "/calendar",
		},
		{
			label: "Settings",
			href: "/settings",
		},
		{
			label: "Help & Feedback",
			href: "/help-feedback",
		},
		{
			label: "Logout",
			href: "/logout",
		},
	],
	titleDescription: {
		esES: "Descripción",
		enUS: "Description",
		esMX: "Descripción",
		arAE: "وصف",
		deDE: "Beschreibung",
		frFR: "Description",
		idID: "Deskripsi",
		itIT: "Descrizione",
		jaJP: "説明",
		koKR: "설명",
		plPL: "Opis",
		ptBR: "Descrição",
		ruRU: "Описание",
		thTH: "คำอธิบาย",
		trTR: "Açıklama",
		viVN: "Mô tả",
		zhCN: "描述",
		zhTW: "描述"
	},
	links: {
		github: "https://github.com/nextui-org/nextui",
		twitter: "https://twitter.com/getnextui",
		docs: "https://nextui-docs-v2.vercel.app",
		discord: "https://discord.gg/9b6yyZKmH4",
		sponsor: "https://patreon.com/jrgarciadev"
	},
};
